name: retinamnist_const
hyperparameters:
    global_batch_size: 128
    data_flag: retinamnist
    model_flag: resnet18
    lr:
        type: log
        base: 10
        minval: -5
        maxval: 0
    gamma: 0.1
    resize: False
    task: "multi-class"
    num_epochs: 15
# data:
#   url: https://medmnist-pathmnist.s3.us-east-2.amazonaws.com/pathmnist.npz
min_validation_period:
    epochs: 1
records_per_epoch: 1080 
searcher:
    name: adaptive_asha
    metric: test_loss
    smaller_is_better: true
    max_length: 
      epochs: 15
    max_trials: 16
    mode: aggressive
resources:
    slots_per_trial: 2
entrypoint: model_def:MyMEDMnistTrial
max_restarts: 0
checkpoint_policy: all


